### ISSUE TITLE
p7zip

### ISSUE THREAD

**Issue by circuit-static** [free5ty1e/primestationone#1] opened 2015-02-17 16:13 UTC
After a fresh load when attempting to use the shell script (megaInstallThemePrimeStationOne.sh) to update the PrimeStation One theme, it failed because I did not have p7zip.

Corrected issue with sudo apt-get install -y p7zip

Is it in the package installs?

**Comment by free5ty1e** [comment] 2015-02-17 18:41
p7zip should be in the list of runtime packages to install, which happens during the `quickUpdatePrimestationOneFiles.sh` script.  

When starting fresh from the latest v0.970 2GB SD image, these runtime packages haven't actually been installed yet due to space concerns on the 2GB image.  

Definitely the first thing to do after expanding the filesystem or transferring to USB is to run the `quickUpdatePrimestationOneFiles.sh` script now that there is room to install the things.  

Good issue to note, I'm sure others will encounter this situation!

**Comment by circuit-static** [comment] 2015-02-17 18:46
Cool, since I am going through the load again because of Issue #2 I will make sure I do it this way (I thought I did) and note my results after

**Comment by free5ty1e** [comment] 2015-02-18 07:46
Confirmed p7zip is in runtime package install script's list of packages to install `installAptRuntimePackages.sh` -- which is called during `quickUpdatePrimestationOneFiles`.

**Comment by free5ty1e** [comment] 2015-02-18 07:48
Of course reopen the issue if it happens again!

**Comment by free5ty1e** [comment] 2015-02-18 07:48
lol - meant to click the other button.

**Closed by free5ty1e** 2015-02-18 07:48 UTC
