### ISSUE TITLE
Loading ROMs from Mega breaks install.

### ISSUE THREAD

**Issue by circuit-static** [free5ty1e/primestationone#2] opened 2015-02-17 18:09 UTC
I have now tested twice from clean loads. Everything works fine, I can load our updated theme, Emulation Station launches... all good.

Then, when I load ROMs from Mega using one of the install scripts I lose keyboard ability and Emulation Station will not fully load after reboot.

I will try additional work-around, but I currently cannot load any ROMs from Mega.

The only way I have found to get my keyboard back so far is to reload

After looking at the error more, it appears that it broke some type of permissions to the ROMs directory and USB interfaces to my Bluetooth Adapter and Keyboard. [Picture of Error to Follow]

I attempted to reboot with nothing but the keyboard attached and still cannot proceed without reload (near as I can tell)

**Comment by free5ty1e** [comment] 2015-02-17 18:32
Yes, I've just come across this myself using the latest v0.970 image, freshly flashed to 2GB SD and then transferred to 16GB USB.  I did everything in one big command and discovered afterwards that Emulationstation crashes during boot, complains about some file permissions (this is probably the cause), and then keyboard is unresponsive.  I have not yet tried to SSH in to remediate the situation, but a hard reboot certainly fixes nothing.

**Comment by free5ty1e** [comment] 2015-02-17 18:38
A thought occurs, the first thing I want to try to SSH in and run this command, to see if it allows EmulationStation to start up after a reboot:

```
chmod -R 777 ~/RetroPie
```

I realize this will have the side effect of making all of the ROMS and BIOS files executable, but who cares for the moment?

**Comment by circuit-static** [comment] 2015-02-17 18:41
By the time I saw these posts, I already loaded the SD card. I will try this if I end up in the same place again

**Comment by free5ty1e** [comment] 2015-02-18 03:02
Yep!  Confirmed, if I SSH in from my Mac and run that command, then reboot, the problem is fixed.  I will add this to the mega install scripts to enforce usable permissions.

**Comment by free5ty1e** [comment] 2015-02-18 07:45
https://github.com/free5ty1e/primestationone/pull/3 fixes this.

**Closed by free5ty1e** 2015-02-18 07:45 UTC
